name: 'xtp-ci'
description: 'Run XTP plugins'
inputs:
  action:
    description: Which action to run
    required: true
    default: checkRepo
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - name: XTP CI
      shell: bash
      run: |
        node dist/index.js ${{ inputs.action }}

