name: 'xtp-ci'
description: 'Run XTP plugins'
inputs:
  action:
    description: Which action to run
    required: true
    default: checkRepo
  token:
    description: XTP token
    required: true
  appId:
    description: XTP app ID
    required: true
  guestKey:
    description: XTP guest key
    required: true
    default: ""
  binding:
    description: XTP binding name
    required: true
    default: ""
  args:
    description: Arguments to be passed to plugin
    required: false
runs:
  using: 'composite'
  steps:
    - name: XTP CI
      shell: bash
      run: |
        node dist/index.js ${{ inputs.action }} ${{ inputs.args }}
      env:
        XTP_TOKEN: ${{ inputs.token }}
        XTP_APP_ID: ${{ inputs.appId }}
        XTP_GUEST_KEY: ${{ inputs.guestKey }}
        XTP_BINDING_NAME: $ {{ inputs.binding }}

