version: v1-draft
imports:
  clone:
    description: Clone a Git repo
    input:
      type: string
      description: The URL of the repo to clone
      contentType: text/plain; charset=utf-8
exports:
  checkRepo:
    input:
      type: string
      contentType: text/plain; charset=utf-8
      description: The input string
    output:
      type: string
      contentType: text/plain; charset=utf-8
      description: The input string
