version: v1-draft
imports:
  shell:
    description: Execute a shell command
    input:
      contentType: application/json
      $ref: "#/components/schemas/ShellArgs"
    output:
      contentType: application/json
      $ref: "#/components/schemas/ShellResult"
exports:
  checkRepo:
    description: Check an entire repo
    input:
      description: Information about the current repo
      $ref: "#/components/schemas/RepoInfo"
      contentType: application/json
    output:
      description: Result object
      $ref: "#/components/schemas/CheckResult"
      contentType: application/json
  scanFiles:
    description: Check one file at a time
    input:
      description: Information about the current repo
      $ref: "#/components/schemas/RepoInfo"
      contentType: application/json
    output:
      description: Result object
      $ref: "#/components/schemas/CheckResult"
      contentType: application/json
components:
  schemas:
    ShellArgs:
      description: Shell command arguments
      properties:
        command:
          description: Shell command
          type: array
          items:
            type: string
        dir:
          description: Working directory
          type: string
          nullable: true
    ShellResult:
      description: Result of a call to `shell`
      properties:
        stdout:
          description: Stdout
          type: string
        stderr:
          description: Stderr
          type: string
        exitCode:
          description: Exit code
          type: number
    RepoInfo:
      description: Information about the repo
      properties:
        sha:
          description: Git SHA
          type: string
        branch:
          description: Git branch name
          type: string
        inputFile:
          description: Path to file being checked
          type: string
          nullable: true
    Status:
      description: Enumeration of possible status outcomes
      type: string
      enum:
        - Success
        - Fail
    CheckResult:
      description: Result of running a check
      properties:
        status:
          description: Check status
          $ref: "#/components/schemas/Status"
        message:
          description: Result message
          type: string
